### ISSUE TITLE
Synth Pedal

### ISSUE THREAD

**Issue by mfvargo** [mfvargo/rtjam_rust#117]
Using the new pitch detector, create a pedal that uses the pitch to create synth sounds.  Or maybe an octaver pedal

**Comment by mfvargo** [comment]
This should be on the pedal-board repo now

**Comment by darius61** [comment]
I cloned the repo and tried to add push up folder/ file and am getting an error saying that I don’t have write privileges for that repo.

On Dec 30, 2024, at 10:14 AM, Mike Vargo ***@***.***> wrote:

﻿

This should be on the pedal-board repo now
