### ISSUE TITLE
No Loopback

### ISSUE THREAD

**Issue by mfvargo** [mfvargo/rtjam_rust#79]
Add a toggle setting for settings.json that will disable the local monitoring feed.

This is a new feature requested  by Mark Davis.

the settings should default to false and be enabled by adding

"no_loopback": true

key/value pair to settings.json

**Comment by Zymurge** [comment]
I started the PR for this before I saw the issue, so just referenced it instead.

**Comment by mfvargo** [comment]
closed by PR #80
